<?php
////////////////////////////////////////////////////////////
//////////////値引／割引ステータス
$discount_status_list[0] = "値引";
$discount_status_list[1] = "割引";
//////////////////////////////////

$check_code_list[0] = "未処理";
$check_code_list[1] = "通常該当";
$check_code_list[2] = "金券引該当";
$check_code_list[3] = "割引前該当";
$check_code_list[4] = "割引前金券引該当";
$check_code_list[5] = "複数会計該当";
$check_code_list[6] = "近似値該当";


//////////個人集計方法
$person_how_list[1] = "回数上位";
$person_how_list[2] = "金額上位";
$person_how_list[3] = "特別PT上位";
$person_how_list[4] = "新規・任意PT上位";
$person_how_list[5] = "交換PT上位";



////////////////////////////////////////////////////////////
?>