<?php
/////////制作物リスト
$product_list[1] = "チラシ";
$product_list[2] = "メニュー";
$product_list[3] = "HP新着情報更新";
$product_list[4] = "グルメサイト更新";
$product_list[5] = "POP";
$product_list[6] = "名刺";
$product_list[99] = "その他";

//////////////サイズ
$papersize_list[12] = "A1横";
$papersize_list[13] = "A1縦";
$papersize_list[1] = "A2横";
$papersize_list[2] = "A2縦";
$papersize_list[3] = "A3横";
$papersize_list[4] = "A3縦";
$papersize_list[5] = "A4横";
$papersize_list[6] = "A4縦";
$papersize_list[7] = "A5横";
$papersize_list[8] = "A5縦";
$papersize_list[9] = "A6横";
$papersize_list[10] = "A6縦";
$papersize_list[11] = "名刺";
$papersize_list[14] = "ハガキ(横)";
$papersize_list[15] = "ハガキ(縦)";

//////////////納品先
$delivery_list[1] = "本部";
$delivery_list[2] = "店舗";

//////////////ラミネート
$laminate_list[1] = "有り";
$laminate_list[2] = "無し";

//////////////食品の状態
$foodstatus_list[1] = "宴会用集合写真";
$foodstatus_list[2] = "単品";
$foodstatus_list[3] = "飲料";
$foodstatus_list[4] = "生物料理";
$foodstatus_list[5] = "加熱料理";
$foodstatus_list[6] = "デザート";

//////////////稟議書
$approval_list[1] = "宴会用集合写真";
$approval_list[2] = "制作確定の制作依頼";

//////////////状態
/*
$inorder_status_list[0] = "削除";
$inorder_status_list[1] = "発注申請中";
$inorder_status_list[2] = "営業確認済";
$inorder_status_list[3] = "発注先手配中";
$inorder_status_list[4] = "発注先確認済";
$inorder_status_list[5] = "制作物納品済";
$inorder_status_list[10] = "完了";
$inorder_status_list[99] = "保留中";
*/

$inorder_status_list[0] = "削除";
$inorder_status_list[1] = "発注・納品希望";
$inorder_status_list[2] = "受注確認";
$inorder_status_list[3] = "発注先詳細確認";
$inorder_status_list[4] = "担当者決定";
//$inorder_status_list[5] = "納品予定日決定";
$inorder_status_list[6] = "制作中";
$inorder_status_list[7] = "制作完了";
//$inorder_status_list[8] = "受注責任者確認完了";
//$inorder_status_list[9] = "制作物納品";
//$inorder_status_list[10] = "発注側確認完了";
$inorder_status_list[99] = "保留中";

$inorder_status_list2[0] = "削除";
$inorder_status_list2[1] = "発注・納品希望";
$inorder_status_list2[2] = "受注確認";
$inorder_status_list2[3] = "発注先詳細確認";
$inorder_status_list2[4] = "担当者決定";
$inorder_status_list2[5] = "納品予定日決定";
$inorder_status_list2[6] = "制作中";
$inorder_status_list2[7] = "制作完了";
$inorder_status_list2[8] = "受注責任者確認完了";
$inorder_status_list2[9] = "制作物納品";
$inorder_status_list2[10] = "発注側確認完了";
$inorder_status_list2[99] = "保留中";

/////////////////////////制作物依頼担当者リスト
$order_mg_emp_list['10023'] = "藤田圭介";
$order_mg_emp_list['10228'] = "後藤健仁";
$order_mg_emp_list['10141'] = "淺田和希";
$order_mg_emp_list['10216'] = "芹澤恵美";
$order_mg_emp_list['10231'] = "外注先";




///////////////////////////////////////////////////
?>