<?php

//////////////////////////// チーム背景色
$group_bgcolor[1] = "#ffffbb";
$group_bgcolor[2] = "#bbbbff";
$group_bgcolor[3] = "#bbffbb";
$group_bgcolor[4] = "#ffbbbb";
$group_bgcolor[5] = "#bbffff";
$group_bgcolor[6] = "#ffbbff";
$group_bgcolor[7] = "#88aaff";
$group_bgcolor[8] = "#ff88aa";

$rank_section_list['302'] = 302;
$rank_section_list['303'] = 303;
$rank_section_list['305'] = 305;
$rank_section_list['309'] = 305;
$rank_section_list['310'] = 305;

$rank_section_name['302'] = "ドコモ";
$rank_section_name['303'] = "ａｕ";
$rank_section_name['305'] = "ＳＢ";

//////////////////////////// 大項目背景色
$bcolor[0]="#aaaaaa";
$bcolor[1]="#eeee11";
$bcolor[2]="#ee1111";
$bcolor[3]="#111111";
$bcolor[4]="#ffffdd";
$bcolor[5]="#ddffff";
$bcolor[6]="#ff9f70";
$bcolor[7]="#adff5f";
$bcolor[8]="#e6e6fa";
$bcolor[9]="#ffd700";
$bcolor[10]="#8fbc8f";
$bcolor[11]="#db7093";
$bcolor[12]="#b0c4de";

//////////////////////////// 大項目文字色
$bigcharcolor[0]="#000000";
$bigcharcolor[1]="#000000";
$bigcharcolor[2]="#ffffff";
$bigcharcolor[3]="#ffffff";
$bigcharcolor[4]="#000000";
$bigcharcolor[5]="#000000";
$bigcharcolor[6]="#000000";
$bigcharcolor[7]="#000000";
$bigcharcolor[8]="#000000";
$bigcharcolor[9]="#000000";
$bigcharcolor[10]="#000000";
$bigcharcolor[11]="#000000";
$bigcharcolor[12]="#000000";

//////////////////////////// ランク順位背景色
$rankbgcolor[1]="#fae350";
$rankbgcolor[2]="#ced1d3";
$rankbgcolor[3]="#e0ad7e";

//////////////////////////// キャリア背景色
$carriercolor[302]="#ff6180";
$carriercolor[303]="#f89643";
$carriercolor[305]="#d0d5d3";

//////////////////////////// 曜日設定
$weekname[0] = "日";
$weekname[1] = "月";
$weekname[2] = "火";
$weekname[3] = "水";
$weekname[4] = "木";
$weekname[5] = "金";
$weekname[6] = "土";

//////////////////////////// 曜日色
$weekcolor[0] = "#ff0000";
$weekcolor[1] = "#333333";
$weekcolor[2] = "#333333";
$weekcolor[3] = "#333333";
$weekcolor[4] = "#333333";
$weekcolor[5] = "#333333";
$weekcolor[6] = "#0000ff";
$weekcolor[7] = "#ff0000";


//////////////////////////// 祝日一覧
$syukubi['20200429'] = 1;
$syukubi['20200504'] = 1;
$syukubi['20200505'] = 1;
$syukubi['20200506'] = 1;
$syukubi['20200723'] = 1;
$syukubi['20200724'] = 1;
$syukubi['20200810'] = 1;
$syukubi['20200921'] = 1;
$syukubi['20200922'] = 1;
$syukubi['20201103'] = 1;
$syukubi['20201123'] = 1;
$syukubi['20210101'] = 1;
$syukubi['20210111'] = 1;
$syukubi['20210211'] = 1;
$syukubi['20210223'] = 1;
$syukubi['20210320'] = 1;
$syukubi['20210429'] = 1;
$syukubi['20210503'] = 1;
$syukubi['20210504'] = 1;
$syukubi['20210505'] = 1;
$syukubi['20210719'] = 1;
$syukubi['20210811'] = 1;
$syukubi['20210920'] = 1;
$syukubi['20210923'] = 1;
$syukubi['20211011'] = 1;
$syukubi['20211103'] = 1;
$syukubi['20211123'] = 1;
$syukubi['20220101'] = 1;
$syukubi['20220110'] = 1;
$syukubi['20220211'] = 1;
$syukubi['20220223'] = 1;
$syukubi['20220321'] = 1;
$syukubi['20220429'] = 1;
$syukubi['20220503'] = 1;
$syukubi['20220504'] = 1;
$syukubi['20220505'] = 1;
$syukubi['20220718'] = 1;
$syukubi['20220811'] = 1;
$syukubi['20220919'] = 1;
$syukubi['20220923'] = 1;
$syukubi['20221010'] = 1;
$syukubi['20221103'] = 1;
$syukubi['20221123'] = 1;

//////////////////////////// mail宛先
$mail_send_type[1] = "To";
$mail_send_type[2] = "Cc";
$mail_send_type[3] = "Bcc";

?>