<?php

/////////////////////////// 定数設定  ///////////////
//第ⅹ回決起大会アンケート
$MS_NUMBER = 2020;//2回
$EVENT_DATE = "2020年2月27日";
//主項目数
$MAIN_ITEM_CNT = 1;//A～Eまで
///////////////////////////////////////////配列設定////////////////////////////


$large_alfa[1] = "1";
$large_alfa[2] = "B";
$large_alfa[3] = "C";
$large_alfa[4] = "D";
$large_alfa[5] = "E";
$large_alfa[6] = "F";
$large_alfa[7] = "G";
$large_alfa[8] = "H";
$large_alfa[9] = "I";

$small_alfa[1] = "1";
$small_alfa[2] = "2";
$small_alfa[3] = "3";
$small_alfa[4] = "4";
$small_alfa[5] = "5";
$small_alfa[6] = "f";
$small_alfa[7] = "g";
$small_alfa[8] = "h";
$small_alfa[9] = "iI";

////////////雇用形態
$employee_type_arr[1] = "社員";
$employee_type_arr[2] = "P/A";

//////////所属部署一覧
$belong_arr[1] = "雄大本部";
$belong_arr[2] = "雄大営業部";
$belong_arr[3] = "甲羅沼津";
$belong_arr[4] = "甲羅富士";
$belong_arr[5] = "御甲羅殿場";
$belong_arr[6] = "ゆうが沼津";
$belong_arr[7] = "ゆうが三島";
$belong_arr[8] = "カルビ沼津";
$belong_arr[9] = "カルビ大仁";
$belong_arr[10] = "カルビ御殿場";
$belong_arr[11] = "わが家の台所";
$belong_arr[12] = "赤から三島";
$belong_arr[13] = "赤から沼津";
$belong_arr[14] = "赤から御殿場";
$belong_arr[15] = "赤から富士";
$belong_arr[16] = "赤から函南";
$belong_arr[17] = "フェスタ";
$belong_arr[18] = "えびす家富士";
$belong_arr[19] = "松福呉服町通り";
$belong_arr[32] = "ふたご呉服町";
$belong_arr[36] = "串屋物語";
$belong_arr[37] = "吉祥庵";
$belong_arr[38] = "イマさん";
$belong_arr[20] = "ラジオシティー沼津";
$belong_arr[21] = "ラジオシティー三島";
$belong_arr[22] = "ラジオシティー御殿場";
$belong_arr[23] = "ラジオシティー函南";
$belong_arr[24] = "雄大ゴルフセンター熱函";
$belong_arr[25] = "雄大ゴルフセンター清水町";
$belong_arr[26] = "通信事業部通信本店";
$belong_arr[27] = "通信事業部ドコモ";
$belong_arr[28] = "通信事業部au原";
$belong_arr[33] = "通信事業部au富士見台";
$belong_arr[29] = "通信事業部SB大仁";
$belong_arr[34] = "通信事業部SB下田";
$belong_arr[35] = "通信事業部SB三島";
$belong_arr[30] = "グランジャー";
$belong_arr[31] = "ユアネット";



///////主項目
$item_arr[1] = "決起大会について";

///////副項目
$sub_item_arr[1][1] = "決起大会（1部）";
$sub_item_arr[1][2] = "遊楽道（2部）";
$sub_item_arr[1][3] = "懇親会（3部）";

$sub_item_arr[1][4] = "フリーコメント";


///////選択項目

$option_arr[101][1] = "満足";
$option_arr[101][2] = "普通";
$option_arr[101][3] = "不満";

$option_arr[102][1] = "満足";
$option_arr[102][2] = "普通";
$option_arr[102][3] = "不満";

$option_arr[103][1] = "満足";
$option_arr[103][2] = "普通";
$option_arr[103][3] = "不満";

//////////チェックフラグ


///////////////////////////////////////////配列設定完了////////////////////////////
?>