<?php
/////////slip_typeリスト
$slip_type_list[1] = "出金伝票";
$slip_type_list[2] = "売上計上";
$slip_type_list[3] = "クレジット利用(口振)履歴";
$slip_type_list[4] = "感動体験";

//////////////課税区分
$tax_class_list[5] = "5課税売上にのみ要する課税仕入";
$tax_class_list[7] = "7課税・非課税売上に共通する課税仕入";
$tax_class_list[0] = "0不課税取引(税外取引)";
$tax_class_list[8] = "8非課税仕入・同対価の返還";
$tax_class_list[57] = "57特定課税仕入(課税売上)";
$tax_class_list[1] = "1課税売上";
$tax_class_list[2] = "2輸出売上(課税品の輸出等)";
$tax_class_list[3] = "3非課税売上";
$tax_class_list[6] = "6非課税売上にのみ要する課税仕入";
$tax_class_list[9] = "9課税区分が未確定の取引等";
$tax_class_list[4] = "4有価証券等の譲渡";
$tax_class_list[11] = "11課税売上に係る対価の返還";
$tax_class_list[12] = "12課税売上に係る貸倒れ";
$tax_class_list[21] = "21同輸出に係る対価の返還";
$tax_class_list[25] = "25輸出売上(非課税品の輸出等)";
$tax_class_list[26] = "26同輸出に係る対価の返還";
$tax_class_list[31] = "31非課税売上に係る対価の返還";
$tax_class_list[51] = "51同課税仕入に係る対価の返還";
$tax_class_list[55] = "55輸入課税仕入(課税売上)";
$tax_class_list[61] = "61同課税仕入に係る対価の返還";
$tax_class_list[65] = "65輸入課税仕入(非課税売上)";
$tax_class_list[71] = "71同課税仕入に係る対価の返還";
$tax_class_list[75] = "75輸入課税仕入(課税・非課税売上共通)";
$tax_class_list[58] = "58同特定課税仕入に係る対価の返還";
$tax_class_list[67] = "67特定課税仕入(非課税売上)";
$tax_class_list[68] = "68同特定課税仕入に係る対価の返還";
$tax_class_list[77] = "77特定課税仕入(課税・非課税売上共通)";
$tax_class_list[78] = "78同特定課税仕入に係る対価の返還";

//////////////手数料持ち
$fee_st_list[1] = "弊社負担";
$fee_st_list[2] = "相手先負担";

//////////////仕訳科目
$Journal_code_list[101] = "広告宣伝費";
$Journal_code_list[102] = "販売促進費";
$Journal_code_list[103] = "備品消耗品費";
$Journal_code_list[104] = "旅費交通費";
$Journal_code_list[105] = "荷造発送費";
$Journal_code_list[106] = "外注費";
$Journal_code_list[107] = "支払手数料";
$Journal_code_list[108] = "サーバー使用料";
$Journal_code_list[109] = "厚生費";
$Journal_code_list[110] = "採用費";
$Journal_code_list[111] = "地代家賃";
$Journal_code_list[112] = "修繕費／車両関係費";
$Journal_code_list[113] = "事務用消耗品費";
$Journal_code_list[114] = "通信交通費";
$Journal_code_list[115] = "電気代";
$Journal_code_list[116] = "水道代";
$Journal_code_list[117] = "ガス代";
$Journal_code_list[118] = "租税公課";
$Journal_code_list[119] = "寄付金";
$Journal_code_list[120] = "接待交際費";
$Journal_code_list[121] = "保険料";
$Journal_code_list[122] = "衛生費";
$Journal_code_list[123] = "支払報酬";
$Journal_code_list[124] = "新聞図書費";
$Journal_code_list[125] = "会議費";
$Journal_code_list[126] = "研修費";
$Journal_code_list[127] = "諸会費";
$Journal_code_list[128] = "給与手当";
$Journal_code_list[129] = "雑給";
$Journal_code_list[130] = "法定福利費";
$Journal_code_list[400] = "売上高";
$Journal_code_list[501] = "現金";
$Journal_code_list[502] = "普通預金";
$Journal_code_list[503] = "売掛金";
$Journal_code_list[504] = "立替金";
$Journal_code_list[505] = "仮払金";
$Journal_code_list[506] = "商品仕入高";
$Journal_code_list[601] = "買掛金";
$Journal_code_list[602] = "未払金";
$Journal_code_list[603] = "預り金";

//////////////銀行種類
$bankkind_list[1] = "銀行";
$bankkind_list[2] = "信用金庫";
$bankkind_list[3] = "商工中金";
$bankkind_list[4] = "農業協同組合";
$bankkind_list[5] = "信用組合";
$bankkind_list[6] = "労働金庫";
$bankkind_list[7] = "漁業協同組合";
//////////////銀行種類
$banktype_list[1] = "普通";
$banktype_list[2] = "当座";
$banktype_list[4] = "貯蓄";

//////////////銀行種類
$yournet_department_list[1] = "本部";
$yournet_department_list[100] = "コンシューマ事業部";
$yournet_department_list[200] = "メディア事業部";
$yournet_department_list[300] = "SaaS事業部";


$inorder_status_list[0] = "削除";
$inorder_status_list[1] = "手続中";
$inorder_status_list[2] = "完了";

/////////////////////////制作物依頼担当者リスト

$my_department_id["200724128"] = 100;
$my_department_id["201102275"] = 100;
$my_department_id["201102231"] = 100;
$my_department_id["201102286"] = 100;
$my_department_id["201202445"] = 100;
$my_department_id["201604755"] = 200;
$my_department_id["201602764"] = 300;
$my_department_id["201702912"] = 300;
$my_department_id["201402706"] = 300;
$my_department_id["200904117"] = 300;
$my_department_id["202104032"] = 300;
$my_department_id["201702923"] = 200;

$slack_user_name["10005"] = "katsumata";
$slack_user_name["201201512"] = "m-akiyama";
$slack_user_name["200416643"] = "kondo";
$slack_user_name["200724128"] = "mori";
$slack_user_name["201102275"] = "K-Shiraiwa";
$slack_user_name["201102286"] = "sano";
$slack_user_name["201202445"] = "k-tsuchiya";
$slack_user_name["201402706"] = "y-kamata";
$slack_user_name["200904117"] = "Sakiguchi";
$slack_user_name["201102309"] = "fujita";
$slack_user_name["201102231"] = "y-ueda";
$slack_user_name["201102343"] = "k-kobayashi";
$slack_user_name["201303593"] = "kanou";
$slack_user_name["201604755"] = "k-matsushita";
$slack_user_name["201602764"] = "m-ootsuki";
$slack_user_name["201602865"] = "m-nakanishi";
$slack_user_name["201702912"] = "d-kageshima";
$slack_user_name["201702923"] = "s-suda";
$slack_user_name["201802025"] = "t-miyamoto";
$slack_user_name["202202042"] = "t-kawakubo";
$slack_user_name["201703935"] = "s-mitsumaru";
$slack_user_name["202202053"] = "m-nakano";
$slack_user_name["200104928"] = "takamizawa";
$slack_user_name["200490016"] = "takahashi";
$slack_user_name["200590028"] = "井上由利子";
$slack_user_name["200590073"] = "matsuura";
$slack_user_name["200618490"] = "imai";
$slack_user_name["201103209"] = "松本";
$slack_user_name["201103399"] = "tsuda";
$slack_user_name["201203503"] = "Oono";
$slack_user_name["201402650"] = "Nishihara";
$slack_user_name["201602809"] = "m-morita";
$slack_user_name["201703957"] = "y-satake";
$slack_user_name["201703980"] = "k-inaba";
$slack_user_name["202104032"] = "k-yamanami";
$slack_user_name["201602832"] = "junk";

////////////クレジットリスト
$creditcart_list[1] = "ニコス(0178)";
$creditcart_list[2] = "AMEX(2004)";
$creditcart_list[14] = "NTT_Biz(4394)";
$creditcart_list[3] = "楽天_DEBIT(5543)";
$creditcart_list[4] = "PAYPAY_DEBIT(5015)";
$creditcart_list[5] = "PAYPAY_DEBIT(9526)";
$creditcart_list[6] = "AMEX_mori(2020)";
$creditcart_list[7] = "AMEX_SHIRAIWA(2038)";
$creditcart_list[8] = "楽天_DEBIT_KAMATA(3209)";
$creditcart_list[9] = "楽天_DEBIT_KANOU(4714)";
$creditcart_list[10] = "楽天_DEBIT_INABA(7351)";
$creditcart_list[11] = "PAYPAY_DEBIT_TSUCHIYA(7011)";
$creditcart_list[12] = "PAYPAY_DEBIT_FUJITA(1811)";
$creditcart_list[13] = "楽天_DEBIT_TAKAMIZAWA(3317)";
$creditcart_list[91] = "口座振替(スルガ本店)";
$creditcart_list[92] = "口座振替(三菱UFJ沼津)";



///////////////////////////////////////////////////
?>