<?php
/////////////////contents-type
$content_type_list['jpg'] = "image/jpeg";
$content_type_list['jpeg'] = "image/jpeg";
$content_type_list['png'] = "image/png";
$content_type_list['gif'] = "image/gif";
$content_type_list['bmp'] = "image/x-bmp";
$content_type_list['tiff'] = "image/x-tiff";
$content_type_list['tif'] = "image/x-tiff";
$content_type_list['pict'] = "image/pict";
$content_type_list['pct'] = "image/pict";

/////////////////////////////
$radar_bgcolor_arr[0] = "#ee1111";
$radar_bgcolor_arr[1] = "#11ee11";
$radar_bgcolor_arr[2] = "#1111ee";
$radar_bgcolor_arr[3] = "#11eeee";
$radar_bgcolor_arr[4] = "#ee11ee";
$radar_bgcolor_arr[5] = "#eeee11";
$radar_bgcolor_arr[6] = "#ff9977";
$radar_bgcolor_arr[7] = "#99ff77";
$radar_bgcolor_arr[8] = "#7799ff";
$radar_bgcolor_arr[9] = "#FFFF77";
//////////////////////////////
?>