<?php

/////////////////////////コンテンツリスト
$this->content_list['100'] = "ポータルサイト全体";
$this->content_list['101'] = "日次業績確認";
$this->content_list['102'] = "WEBアンケート";
$this->content_list['103'] = "店長会議資料";

/////////////////////////メニュー大項目
$this->big_item_list['101'] = "全社員共通";
$this->big_item_list['102'] = "個人";
$this->big_item_list['103'] = "マネジメント";
$this->big_item_list['104'] = "業務";
$this->big_item_list['105'] = "書類・ルール";
$this->big_item_list['106'] = "社員向け";
$this->big_item_list['107'] = "他システムリンク";
$this->big_item_list['108'] = "オプション";

/////////////////////////性別リスト
$this->sex_list['m'] = "男性";
$this->sex_list['w'] = "女性";

/////////////////////////企業リスト
$this->company_list[1] = "雄大株式会社";
$this->company_list[3] = "熱函ゴルフセンター有限会社";
$this->company_list[4] = "雄大ゴルフセンター有限会社";
$this->company_list[5] = "株式会社ユアネット";
$this->company_list[6] = "グランジャー株式会社";

/////////////////////////事業部リスト
$this->section_list['003'] = "本社";
$this->section_list['001'] = "営業部";
$this->section_list['101'] = "甲羅沼津";
$this->section_list['102'] = "甲羅富士";
$this->section_list['100'] = "甲羅御殿場";
$this->section_list['111'] = "えびす家富士";
$this->section_list['103'] = "ゆうが沼津";
$this->section_list['104'] = "ゆうが三島";
$this->section_list['107'] = "わが家";
$this->section_list['110'] = "フェスタ";
$this->section_list['115'] = "イマさん沼津";
$this->section_list['116'] = "イマさん静岡";
$this->section_list['108'] = "赤から三島";
$this->section_list['501'] = "赤から沼津";
$this->section_list['503'] = "赤から御殿場";
$this->section_list['502'] = "赤から富士";
$this->section_list['504'] = "赤から函南";
$this->section_list['106'] = "カルビ沼津";
$this->section_list['109'] = "カルビ大仁";
$this->section_list['112'] = "カルビ御殿場";
$this->section_list['105'] = "ふたご";
$this->section_list['204'] = "ラジオ沼津";
$this->section_list['202'] = "ラジオ三島";
$this->section_list['201'] = "ラジオ御殿場";
$this->section_list['205'] = "ラジオ函南";
$this->section_list['113'] = "松福静岡";
$this->section_list['401'] = "吉祥庵沼津";
$this->section_list['402'] = "吉祥庵愛知東郷";
$this->section_list['403'] = "鷹乃静岡";
$this->section_list['404'] = "串屋物語";
$this->section_list['206'] = "しげよし沼津";
$this->section_list['700'] = "VANSAN浜松";
$this->section_list['701'] = "VANSAN富士";
$this->section_list['702'] = "VANSAN沼津";
$this->section_list['897'] = "大韓食堂";
$this->section_list['999'] = "ゆうだい温泉";
$this->section_list['301'] = "通信本店";
$this->section_list['302'] = "ドコモ";
$this->section_list['303'] = "ａｕ原";
$this->section_list['304'] = "ａｕ富士見台";
$this->section_list['305'] = "ＳＢ大仁";
$this->section_list['309'] = "ＳＢ下田";
$this->section_list['310'] = "ＳＢ三島";
$this->section_list['3101'] = "フロント課";
$this->section_list['3102'] = "施設課";
//$this->section_list['004'] = "お掃除";

$this->yournet_section_list['1'] = "管理";
$this->yournet_section_list['3'] = "総務";
$this->yournet_section_list['5'] = "WEB";
$this->yournet_section_list['2'] = "アプリ";
$this->yournet_section_list['8'] = "クリエイター";
$this->yournet_section_list['4'] = "広告";
$this->yournet_section_list['6'] = "サポート";
$this->yournet_section_list['7'] = "サーバ管理";

/////////////////////////事業部グループ
$this->section_group_list['003'] = "'003','001'";
$this->section_group_list['001'] = "'003','001'";
$this->section_group_list['101'] = "'101','102','100','111'";
$this->section_group_list['102'] = "'101','102','100','111'";
$this->section_group_list['100'] = "'101','102','100','111'";
$this->section_group_list['111'] = "'101','102','100','111'";
$this->section_group_list['103'] = "'103','104'";
$this->section_group_list['104'] = "'103','104'";
$this->section_group_list['107'] = "'107','110'";
$this->section_group_list['110'] = "'107','110'";
$this->section_group_list['108'] = "'108','501','503','502','504'";
$this->section_group_list['501'] = "'108','501','503','502','504'";
$this->section_group_list['503'] = "'108','501','503','502','504'";
$this->section_group_list['502'] = "'108','501','503','502','504'";
$this->section_group_list['504'] = "'108','501','503','502','504'";
$this->section_group_list['106'] = "'106','109','112','105'";
$this->section_group_list['109'] = "'106','109','112','105'";
$this->section_group_list['112'] = "'106','109','112','105'";
$this->section_group_list['105'] = "'106','109','112','105'";
$this->section_group_list['204'] = "'204','202','201','205','113','206'";
$this->section_group_list['202'] = "'204','202','201','205','113','206'";
$this->section_group_list['201'] = "'204','202','201','205','113','206'";
$this->section_group_list['205'] = "'204','202','201','205','113','206'";
$this->section_group_list['113'] = "'204','202','201','205','113','206'";
$this->section_group_list['206'] = "'204','202','201','205','113','206'";
$this->section_group_list['401'] = "'401','402','403'";
$this->section_group_list['402'] = "'401','402','403'";
$this->section_group_list['403'] = "'401','402','403'";
$this->section_group_list['301'] = "'301','302','303','304','305','309','310'";
$this->section_group_list['302'] = "'301','302','303','304','305','309','310'";
$this->section_group_list['303'] = "'301','302','303','304','305','309','310'";
$this->section_group_list['304'] = "'301','302','303','304','305','309','310'";
$this->section_group_list['305'] = "'301','302','303','304','305','309','310'";
$this->section_group_list['309'] = "'301','302','303','304','305','309','310'";
$this->section_group_list['310'] = "'301','302','303','304','305','309','310'";
$this->section_group_list['004'] = "'004'";
$this->section_group_list['897'] = "'897'";
$this->section_group_list['999'] = "'999'";

/////////////////////////雇用区分
$this->employee_type_list[1] = "役員";
$this->employee_type_list[2] = "兼務役員";
$this->employee_type_list[3] = "社員";
$this->employee_type_list[4] = "準社員";
$this->employee_type_list[5] = "契約社員";
$this->employee_type_list[6] = "パート・アルバイト";
$this->employee_type_list[7] = "嘱託";
$this->employee_type_list[8] = "短期";
$this->employee_type_list[9] = "派遣";
$this->employee_type_list[90] = "P/A共通アカウント";
$this->employee_type_list[99] = "その他";

$this->yournet_type_list[6] = 1;
$this->yournet_type_list[7] = 3;
$this->yournet_type_list[8] = 3;
$this->yournet_type_list[1] = 3;
$this->yournet_type_list[2] = 5;
$this->yournet_type_list[3] = 6;
$this->yournet_type_list[4] = 9;
$this->yournet_type_list[5] = 99;


/////////////////////////役職区分
$this->position_class_list[10] = "会長・社長";
$this->position_class_list[20] = "役員クラス";
$this->position_class_list[30] = "部長クラス";
$this->position_class_list[40] = "マネージャークラス";
$this->position_class_list[50] = "店長・料理長・課長クラス";
$this->position_class_list[60] = "役職者及び係長クラス";
$this->position_class_list[70] = "主任クラス";
$this->position_class_list[90] = "一般";

$this->yournet_class_list[6] = 20;
$this->yournet_class_list[7] = 40;
$this->yournet_class_list[8] = 70;
$this->yournet_class_list[1] = 90;
$this->yournet_class_list[2] = 90;
$this->yournet_class_list[3] = 90;
$this->yournet_class_list[4] = 90;
$this->yournet_class_list[5] = 90;

/////////////////////////権限区分
$this->auth_list[1] = "全権";
$this->auth_list[5] = "所属のみ";
$this->auth_list[9] = "権利無し";

/////////////////////////管理者権限
$this->admin_auth_list[0] = "無し";
$this->admin_auth_list[1] = "全て有り";
$this->admin_auth_list[2] = "同系列部署・店舗のみ有り";
$this->admin_auth_list[3] = "所属部署・店舗のみ有り";

/////////////////////////退職チェック対象
$this->nodel_flag_list[0] = "対象";
$this->nodel_flag_list[1] = "対象外";

//////////////////////////////文書管理タイプリスト
$this->type_list[1] = "folder";
$this->type_list[2] = "file";

//////////////////////////////お知らせstatusリスト
$this->message_status_list[0] = "削除";
$this->message_status_list[1] = "未読";
$this->message_status_list[2] = "既読";

//////////////////////////////相談提案r_flagリスト
$this->consult_rflag_list[0] = "削除";
$this->consult_rflag_list[1] = "未読";
$this->consult_rflag_list[2] = "既読";
$this->consult_rflag_list[3]= "返信済";
$this->consult_rflag_list[4]= "確認中";
$this->consult_rflag_list[5] = "検討中";
$this->consult_rflag_list[6] = "保留中";
$this->consult_rflag_list[7] = "対応中";
$this->consult_rflag_list[8] = "将来的に検討";
$this->consult_rflag_list[9] = "解決済";

//////////////////////////////書類管理リスト
$this->docu_kind_list[1] = "社内規則・ルール";
$this->docu_kind_list[2] = "議事録";
$this->docu_kind_list[3] = "マニュアル";
$this->docu_kind_list[4] = "経営計画・ビジョン";
$this->docu_kind_list[5] = "社内書類";
$this->docu_kind_list[6] = "共有ファイル";

//////////////////////////////書類管理リスト
$this->pdca_purpose_list[1] = "フリー対策";
$this->pdca_purpose_list[2] = "予約対策";
$this->pdca_purpose_list[3] = "人件費";
$this->pdca_purpose_list[4] = "原価";
$this->pdca_purpose_list[5] = "その他";
$this->pdca_purpose_list[6] = "ふぁんくる対策";

//////////////////////////////menu statusリスト
$this->menu_status_list[0] = "削除";
$this->menu_status_list[1] = "表示";
$this->menu_status_list[2] = "リンク無効";

/////////////////////////雇用状態
$this->employee_status_list[1] = "在職";
$this->employee_status_list[2] = "退職";

/////////////////////////雇用状態
$this->test_user[10211] = "302";

/////////////////////////対応コンテンツタイプ
$this->mime_type["pdf"] = "application/pdf";
$this->mime_type["txt"] = "text/plain";
$this->mime_type["jpg"] = "image/jpeg";
$this->mime_type["jpeg"] = "image/jpeg";
$this->mime_type["png"] = "image/png";
$this->mime_type["gif"] = "image/gif";
$this->mime_type["mp4"] = "video/mp4";
$this->mime_type["mov"] = "video/quicktime";
$this->mime_type["avi"] = "video/x-msvideo";
$this->mime_type["mpeg"] = "video/mpeg";
$this->mime_type["mpg"] = "video/mpeg";
$this->mime_type["swf"] = "application/x-shockwave-flash";
$this->mime_type["webm"] = "video/webm";
$this->mime_type["ogv"] = "video/ogg";
$this->mime_type["doc"] = "application/msword";
$this->mime_type["xls"] = "application/vnd.ms-excel";
$this->mime_type["ppt"] = "application/vnd.ms-powerpoint";
$this->mime_type["docx"] = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
$this->mime_type["xlsx"] = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
$this->mime_type["pptx"] = "application/vnd.openxmlformats-officedocument.presentationml.presentation";

/////////////////////////店舗番号→POS_SHOP_NO対応
$this->section_to_pos['101'] = 1;		//沼津甲羅
$this->section_to_pos['102'] = 2;		//富士甲羅
$this->section_to_pos['100'] = "";	//甲羅御殿場
$this->section_to_pos['111'] = 20;	//えびす家 
$this->section_to_pos['103'] = 4;		//ゆうが沼津
$this->section_to_pos['104'] = 9;		//ゆうが三島
$this->section_to_pos['107'] = "";	//わが家
$this->section_to_pos['110'] = 19;	//フェスタ
$this->section_to_pos['115'] = 28;	//イマさん
$this->section_to_pos['116'] = 31;	//イマさん静岡
$this->section_to_pos['108'] = 10;	//赤から三島
$this->section_to_pos['501'] = 11;	//赤から沼津
$this->section_to_pos['503'] = 14;	//赤から御殿場
$this->section_to_pos['502'] = 15;	//赤から富士 
$this->section_to_pos['504'] = 16;	//赤から函南
$this->section_to_pos['106'] = 3;		//カルビ沼津
$this->section_to_pos['109'] = 12;	//カルビ大仁
$this->section_to_pos['112'] = 21;	//カルビ御殿場
$this->section_to_pos['105'] = "";	//ふたご 
$this->section_to_pos['204'] = 5;		//ラジオ沼津
$this->section_to_pos['202'] = 6;		//ラジオ三島 
$this->section_to_pos['201'] = 18;	//ラジオ御殿場
$this->section_to_pos['205'] = "";	//ラジオ函南
$this->section_to_pos['113'] = "";	//松福静岡
$this->section_to_pos['401'] = "";	//吉祥庵沼津
$this->section_to_pos['402'] = "";	//吉祥庵愛知東郷
$this->section_to_pos['404'] = "";	//串屋物語
$this->section_to_pos['700'] = "";	//VANSAN浜松
$this->section_to_pos['897'] = "32";	//VANSAN浜松
$this->section_to_pos['3001'] = "13";	//雄大ゴルフ熱函
$this->section_to_pos['3002'] = "22";	//雄大ゴルフ清水町

/////////////////////////ポイントカード店舗コード→店舗番号対応
$this->mpt_to_section['6000'] = '001';		//沼津甲羅
$this->mpt_to_section['6001'] = '101';		//沼津甲羅
$this->mpt_to_section['6002'] = '102';		//富士甲羅
$this->mpt_to_section['6003'] = '100';	//甲羅御殿場
$this->mpt_to_section['6202'] = '111';	//えびす家 
$this->mpt_to_section['6201'] = '103';		//ゆうが沼津
$this->mpt_to_section['6203'] = '104';		//ゆうが三島
//$this->mpt_to_section['107'] = '107';	//わが家
$this->mpt_to_section['6801'] = '110';	//フェスタ
$this->mpt_to_section['6204'] = '115';	//イマさん
//$this->mpt_to_section['116'] = '116';	//イマさん静岡
$this->mpt_to_section['6601'] = '108';	//赤から三島
$this->mpt_to_section['6602'] = '501';	//赤から沼津
$this->mpt_to_section['6603'] = '503';	//赤から御殿場
$this->mpt_to_section['6604'] = '502';	//赤から富士 
$this->mpt_to_section['6605'] = '504';	//赤から函南
$this->mpt_to_section['6301'] = '106';		//カルビ沼津
$this->mpt_to_section['6302'] = '109';	//カルビ大仁
$this->mpt_to_section['6303'] = '112';	//カルビ御殿場
//$this->mpt_to_section['105'] = '105';	//ふたご
$this->mpt_to_section['6101'] = '204';		//ラジオ沼津
$this->mpt_to_section['6103'] = '202';		//ラジオ三島 
$this->mpt_to_section['6104'] = '201';	//ラジオ御殿場
$this->mpt_to_section['6105'] = '205';	//ラジオ函南
//$this->mpt_to_section['113'] = '113';	//松福静岡
//$this->mpt_to_section['401'] = '401';	//吉祥庵沼津
//$this->mpt_to_section['402'] = '402';	//吉祥庵愛知東郷
//$this->mpt_to_section['404'] = '404';	//串屋物語
$this->mpt_to_section['6205'] = '701';	//VANSAN富士
//$this->mpt_to_section['700'] = '700';	//VANSAN浜松
$this->mpt_to_section['6400'] = "301";//通信本店
$this->mpt_to_section['6401'] = "302";//ドコモ
$this->mpt_to_section['6402'] = "303";//ａｕ原
//$this->mpt_to_section['304'] = "304";//ａｕ富士見台
$this->mpt_to_section['6405'] = "305";//ＳＢ大仁
//$this->mpt_to_section['309'] = "309";//ＳＢ下田
//$this->mpt_to_section['310'] = "310";//ＳＢ三島
$this->mpt_to_section['6701'] = "3001";	//雄大ゴルフ熱函
$this->mpt_to_section['6702'] = "3002";	//雄大ゴルフ清水町

/////////////////////////POS ttend メディア種別　明細種別リスト
$this->media_detail_list[2] = "掛計(社内)";
$this->media_detail_list[3] = "ＰａｙＰａｙ";
$this->media_detail_list[4] = "掛計(その他)";
$this->media_detail_list[5] = "ｸﾚｼﾞｯﾄｶｰﾄﾞ";
$this->media_detail_list[6] = "電子マネー";
$this->media_detail_list[8] = "市町村ｸｰﾎﾟﾝ･紙(市町村)";
$this->media_detail_list[9] = "市町村ｸｰﾎﾟﾝ･電子(市町村)";
$this->media_detail_list[10] = "地域共通ｸｰﾎﾟﾝ･紙(GoToﾄﾗﾍﾞﾙ)";
$this->media_detail_list[11] = "地域共通ｸｰﾎﾟﾝ･電子(GoToﾄﾗﾍﾞﾙ)";
$this->media_detail_list[12] = "ﾌﾟﾚﾐｱﾑ食事券(GoToEat)";
$this->media_detail_list[13] = "ヤフーロコＰ(GoToWeb)";
$this->media_detail_list[14] = "レッティーＰ(GoToWeb)";
$this->media_detail_list[15] = "ｄﾎﾟｲﾝﾄ利用";
$this->media_detail_list[16] = "ｄ払い";
$this->media_detail_list[17] = "ａｕｐａｙ";
$this->media_detail_list[18] = "ぐるなびＰ(GoToWeb)";
$this->media_detail_list[19] = "食べログＰ(GoToWeb)";
$this->media_detail_list[20] = "ﾎｯﾄﾍﾟｯﾊﾟ-Ｐ(GoToWeb)";


/////////////////////////アンケート
/////////////////////////メディア種類
$this->mediatype_list[0] = "ダイレクト";
$this->mediatype_list[1] = "QRコード";
$this->mediatype_list[2] = "iOSアプリ";
$this->mediatype_list[3] = "Androidアプリ";
$this->mediatype_list[4] = "LINE";

/////////////////////////回答種類
$this->answer_kind_list[1] = "なし";
$this->answer_kind_list[2] = "表示のみ";
$this->answer_kind_list[3] = "いいえクリック";
$this->answer_kind_list[9] = "クリック有";

/////////////////////////チェックリスト";
$this->check_flag_list[0] = "未確認";
$this->check_flag_list[1] = "確認済";
$this->check_flag_list[2] = "落選";
$this->check_flag_list[3] = "当選";
$this->check_flag_list[8] = "当選発送済";
$this->check_flag_list[9] = "当選受取済";

/////////////////////////事業部リストポイントカード
$this->mpt_shop_list['001'] = "ゴールドカード";
$this->mpt_shop_list['101'] = "甲羅沼津";
$this->mpt_shop_list['102'] = "甲羅富士";
$this->mpt_shop_list['100'] = "甲羅御殿場";
$this->mpt_shop_list['111'] = "えびす家富士";
$this->mpt_shop_list['103'] = "ゆうが沼津";
$this->mpt_shop_list['104'] = "ゆうが三島";
$this->mpt_shop_list['110'] = "フェスタ";
$this->mpt_shop_list['115'] = "イマさん沼津";
$this->mpt_shop_list['108'] = "赤から三島";
$this->mpt_shop_list['501'] = "赤から沼津";
$this->mpt_shop_list['503'] = "赤から御殿場";
$this->mpt_shop_list['502'] = "赤から富士";
$this->mpt_shop_list['504'] = "赤から函南";
$this->mpt_shop_list['106'] = "カルビ沼津";
$this->mpt_shop_list['109'] = "カルビ大仁";
$this->mpt_shop_list['112'] = "カルビ御殿場";
$this->mpt_shop_list['701'] = "VANSAN富士";
//$this->mpt_shop_list['105'] = "ふたご";
$this->mpt_shop_list['204'] = "ラジオ沼津";
$this->mpt_shop_list['202'] = "ラジオ三島";
$this->mpt_shop_list['201'] = "ラジオ御殿場";
$this->mpt_shop_list['205'] = "ラジオ函南";
//$this->mpt_shop_list['113'] = "松福静岡";
//$this->mpt_shop_list['401'] = "吉祥庵沼津";
//$this->mpt_shop_list['402'] = "吉祥庵愛知東郷";
//$this->mpt_shop_list['404'] = "串屋物語";
//$this->mpt_shop_list['700'] = "VANSAN浜松";
$this->mpt_shop_list['301'] = "通信事業部";
$this->mpt_shop_list['302'] = "ドコモ";
$this->mpt_shop_list['303'] = "ａｕ原";
$this->mpt_shop_list['305'] = "ＳＢ大仁";
$this->mpt_shop_list['3001'] = "雄大ゴルフ熱函";
$this->mpt_shop_list['3002'] = "雄大ゴルフ清水町";

/////////////////////////binoID変換
$this->scraing_shop_list['101'] = '00001';//"甲羅沼津";
$this->scraing_shop_list['102'] = '00002';//"甲羅富士";
//$this->scraing_shop_list['100'] = '00017';//"甲羅御殿場";
$this->scraing_shop_list['111'] = '00020';//"えびす家富士";
$this->scraing_shop_list['103'] = '00004';//"ゆうが沼津";
$this->scraing_shop_list['104'] = '00009';//"ゆうが三島";
$this->scraing_shop_list['110'] = '00019';//"フェスタ";
$this->scraing_shop_list['115'] = '00028';//"イマさん沼津";
$this->scraing_shop_list['116'] = '00031';	//イマさん静岡
$this->scraing_shop_list['108'] = '00010';//"赤から三島";
$this->scraing_shop_list['501'] = '00011';//"赤から沼津";
$this->scraing_shop_list['503'] = '00014';//"赤から御殿場";
$this->scraing_shop_list['502'] = '00015';//"赤から富士";
$this->scraing_shop_list['504'] = '00016';//"赤から函南";
$this->scraing_shop_list['106'] = '00003';//"カルビ沼津";
$this->scraing_shop_list['109'] = '00012';//"カルビ大仁";
$this->scraing_shop_list['112'] = '00021';//"カルビ御殿場";
$this->scraing_shop_list['105'] = '00025';//"ふたご";
$this->scraing_shop_list['204'] = '00005';//"ラジオ沼津";
$this->scraing_shop_list['202'] = '00006';//"ラジオ三島";
$this->scraing_shop_list['201'] = '00018';//"ラジオ御殿場";
$this->scraing_shop_list['205'] = '00023';//"ラジオ函南";
$this->scraing_shop_list['206'] = '00206';//"しげよし沼津";
$this->scraing_shop_list['113'] = '00024';//"松福静岡";
$this->scraing_shop_list['401'] = '00026';//"吉祥庵沼津";
$this->scraing_shop_list['402'] = '00030';//"吉祥庵愛知東郷";
$this->scraing_shop_list['404'] = '00027';//"串屋物語";
$this->scraing_shop_list['700'] = '00029';//"VANSAN浜松";
$this->scraing_shop_list['701'] = '00701';//"VANSAN富士";

/////////////////////////アンケートカテゴリ
$this->survey_cate_list['1'] = "来店動機";
$this->survey_cate_list['2'] = "NPS";
$this->survey_cate_list['3'] = "サービス(S)";
$this->survey_cate_list['4'] = "クオリティ(Q)";
$this->survey_cate_list['5'] = "クレンリネス(C)";

/////////////////////////アンケートプライバシー
$this->survey_privacy_list['1'] = "個人情報(低)";
$this->survey_privacy_list['2'] = "個人情報(中)";
$this->survey_privacy_list['3'] = "個人情報(高)";

/////////////////////////アンケートログ
$this->survey_log_list['1'] = "個人情報データ閲覧";
$this->survey_log_list['2'] = "個人情報データDL";
$this->survey_log_list['9'] = "データ削除";

/////////////////////////アンケート基準値
$this->survey_assess_base_list[1] = 4.0;
$this->survey_assess_base_list[2] = 4.5;

/////////////////////////アンケート基準値色
$this->survey_assess_base_color[1] = "#ee4444";
$this->survey_assess_base_color[2] = "#ff8c00";
$this->survey_assess_base_color[3] = "#4444ee";

/////////////////////////週毎表示
$this->p_week_list[0] = "全日数";
$this->p_week_list[1] = "1週(1-7日)";
$this->p_week_list[2] = "2週(8-14日)";
$this->p_week_list[3] = "3週(15-21日)";
$this->p_week_list[4] = "4週(22-28日)";
$this->p_week_list[5] = "5週(29-末日)";

/////////////////////////アンケート種類
$this->survey_type_list[1] = "記述式(1行のみ)";
$this->survey_type_list[2] = "記述式(複数行)";
$this->survey_type_list[3] = "ラジオボタン(1択のみ)";
$this->survey_type_list[4] = "チェックボックス(複数選択)";
$this->survey_type_list[5] = "プルダウン選択式";
//$this->survey_type_list[6] = "シングルグリッド(ラジオボタン)";
//$this->survey_type_list[7] = "マルチグリッド(ラジオボタン)";
//$this->survey_type_list[8] = "マルチグリッド(チェックボックス)";
//$this->survey_type_list[9] = "ファイルアップロード";
//$this->survey_type_list[10] = "日付";
//$this->survey_type_list[11] = "時刻";
//$this->survey_type_list[12] = "Eメール記述式";
$this->survey_type_list[99] = "テキスト表示のみ";

/////////////////////////アンケート誘導種類
$this->survey_jump_type_list[0] = "誘導なし";
$this->survey_jump_type_list[1] = "手動(はい・いいえ式)";
$this->survey_jump_type_list[2] = "強制(はい・いいえ表示)";
$this->survey_jump_type_list[3] = "POPアップ手動(はい・いいえ式)";
$this->survey_jump_type_list[4] = "POPアップ強制(はい・いいえ表示)";
?>